name: "Create release"

on:
  push:
    tags:
      - '*'

concurrency: release

jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.0"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: Build phar
        run: |
          composer run box-install
          composer run box-build
          composer run box-info

      - name: "Create release"
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true

      - name: "Upload drupalorg.phar"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./drupalorg.phar
          asset_name: drupalorg.phar
          asset_content_type: application/octet-stream
